### ISSUE TITLE
Research replacing jsqmessagesviewcontroller 

### ISSUE THREAD

**Issue by carmenlau** [SkygearIO/chat-SDK-iOS#119]
https://github.com/MessageKit/MessageKit

@ben181231 should make a choice base on the following criteria:

* Write from zero is not an option
* We will fork both jsq or messagekit anyway, so the choice should base on the presence of the library, not future of the library.
* Maintain upstream relationship is not a priority
* If it is easier to upgrade jsqmessagesview to Swift 4, or replace MessageKit?
* Which one is easier to customise (to what we want)?

**Comment by chpapa** [comment]
Conclusion:

@ben181231 should make a choice base on the following criteria:

* @rickmak Write from zero is not an option
* @Steven-Chan We will fork both jsq or messagekit anyway, so the choice is basically based on the present of the library, not future of the library.
* Choices: if it is easier to upgrade jsqmessagesview to Swift 4, or replace MessageKit?
* @rickmak maintain upstream relationship is not a priority

**Comment by Steven-Chan** [comment]
I want to add one more criteria, not sure if it does makes sense @chpapa @rickmak @ben181231 .

We should choose one that is easier to customise (to what we want).

When I was adding a camera button to the conversation view input tool bar, I find jsq is not friendly for more than one side button at each side. So I need to do some extra layout to overcome this restriction, which I think would be hard to maintain. I think this is because jsq is based on the the old design of iMessage, and this is probably not what we want.

I am not sure if changing to messagekit would help this situation, but this would probably affect our future.

**Comment by chpapa** [comment]
@Steven-Chan sure, I have summarized it to the main points in the description.

**Comment by carmenlau** [comment]
We don't have plain to replace it for now
