### ISSUE TITLE
[UIKit] Support showing another users' name for conversation title

### ISSUE THREAD

**Issue by mayyuen318** [SkygearIO/chat-SDK-iOS#80]
<img width="306" alt="screen shot 2017-10-17 at 12 23 15 am" src="https://user-images.githubusercontent.com/7130966/31623869-735c1574-b2d3-11e7-9995-96fe859efa52.png">
This is a bug i bumped into when I tried Zachary's Demo
I should be having a conversation with Ten. The top should be Ten instead of my username maytest.
This only happens in 1 on 1 conversation. Group conversation doesn't have this problem.

**Comment by mayyuen318** [comment]
@carmenlau Not sure who should I assign to. Please help to re-assign

**Comment by chpapa** [comment]
more information: it is because currently the UIkit title display the conversation name, however in many occasions people prefer to display all usernames currently in the conversation (especially when the conversation is one on one)

two idea of how to close this issue:

1. have an option in conversationview, to choose display conversation title, or usernames of the users in this conversation except the current user

b. for direct conversation, display other users by default.

**Comment by mayyuen318** [comment]
For 'have an option in conversationview, to choose display conversation title, or usernames of the users in this conversation except the current user'
@chpapa 
Sorry I might misunderstand. 
usernames of the users --> Do you mean group chat? For group chat more of the applications should have a page for filling the name of the conversation and the displayed name should be the the one they input.

**Comment by chpapa** [comment]
@mayyuen318 Yes that's exactly what it is.
